apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
  name: devrapid-temp
  namespace: nais-analyse
  labels:
    team: nais-analyse
spec:
  pool: nav-prod
  config:  # optional; all fields are optional too; defaults shown
    cleanupPolicy: delete  # delete, compact
    minimumInSyncReplicas: 1
    partitions: 1
    replication: 2  # see min/max requirements
    retentionBytes: -1  # -1 means unlimited
    retentionHours: -1  # -1 means unlimited
  acl:
    - team: nais-analyse
      application: devrapid-git-push
      access: readwrite   # read, write, readwrite