name: "Build and deploy devrapid-git-push"

on:
  push:
    branches:
      - "main"

env:
  "IMAGE": "docker.pkg.github.com/${{ github.repository }}/devrapid-git-push:${{ github.sha }}"

jobs:
  build:
    name: "build"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5" # ratchet:actions/checkout@v2
      - uses: "gradle/wrapper-validation-action@56b90f209b02bf6d1deae490e9ef18b21a389cd4" # ratchet:gradle/wrapper-validation-action@v1
      - uses: "actions/cache@8492260343ad570701412c2f464a5877dc76bace" # ratchet:actions/cache@v2
        with:
          "path": "~/.gradle/caches"
          "key": "${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle.kts') }}"
          "restore-keys": "${{ runner.os }}-gradle-"
      - uses: "actions/setup-java@b6e674f4b717d7b0ae3baee0fbe79f498905dfde" # ratchet:actions/setup-java@v1
        with:
          "java-version": "17"
      - name: "compile and run tests"
        run: "./gradlew build"
      - name: Install cosign
        uses: sigstore/cosign-installer@6e04d228eb30da1757ee4e1dd75a0ec73a653e06 # ratchet:sigstore/cosign-installer@main
        with:
          cosign-release: 'v2.0.0'
      - name: Verify distroless base image
        run: cosign verify --certificate-identity "keyless@distroless.iam.gserviceaccount.com" --certificate-oidc-issuer "https://accounts.google.com" $BASEIMAGE
      - name: "Build and publish Docker image"
        run: "docker build --pull --tag ${IMAGE} . && echo $GITHUB_TOKEN | docker login --username $GITHUB_REPOSITORY --password-stdin https://docker.pkg.github.com && docker push ${IMAGE}"
        env:
          "GITHUB_TOKEN": "${{ secrets.GITHUB_TOKEN }}"

  deployToProd:
    name: "Deploy to prod"
    needs:
      - "build"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5" # ratchet:actions/checkout@v2
      - name: "Deploy to prod-gcp"
        uses: "nais/deploy/actions/deploy@b48fd255a02170cdb67cbc74cb52b5d3016975f8" # ratchet:nais/deploy/actions/deploy@v1
        env:
          "APIKEY": "${{ secrets.NAIS_DEPLOY_APIKEY }}"
          "CLUSTER": "prod-gcp"
          "RESOURCE": ".nais/nais.yaml,.nais/topic.yaml"
          "VARS": ".nais/prod.yaml"
